language: csharp
solution: AutoDependencyDetector.sln
install:
  - nuget restore AutoDependencyDetector.sln
  - nuget install NUnit.Runners -Version 3.6.1 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release AutoDependencyDetector.sln
  - mono ./testrunner/NUnit.Runners.3.6.1/tools/nunit-console.exe .AutoDependencyDetectorTests\bin\Release\*Tests.dll