language: csharp
solution: AutoDependencyDetector.sln
install:
  - nuget restore AutoDependencyDetector.sln
  - nuget install NUnit.Runners -Version 3.6.1 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release /t:DownloadDependencyWalker AutoDependencyDetector.sln
  - xbuild /p:Configuration=Release AutoDependencyDetector.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe ./AutoDependencyDetectorTests/bin/Release/*Tests.dll